#logging :
#  file:
#    path: logs
#  level:
#    "com.toy.mealimeter" : "info"

spring:
  datasource:
    url: jdbc:mysql://mealimeter.cng3wp3rp9ml.ap-northeast-2.rds.amazonaws.com:3306/mealimeter?serverTimezone=Asia/Seoul&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true
    username: admin
    password: fine0042*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create
  security:
    user:
      password: 1234

server:
  port: 3590
