spring:
  datasource:
    url: jdbc:mysql://mealimeter.cng3wp3rp9ml.ap-northeast-2.rds.amazonaws.com:3306/mealimeter?serverTimezone=Asia/Seoul&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true
    username: admin
    password: fine0042*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
  profiles:
    active: local

security:
  firebase-props:
    database-url: https://mealimeter-75af5.firebaseio.com
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: ${CORS_DOMAIN}
    path: /
  allow-credentials: true
  allowed-origins:
    - https://${CORS_DOMAIN}
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /public/*
  exposed-headers:
    - X-Xsrf-Token

logging:
  level:
#    org:
#      springframework:
#        security: DEBUG
    root: INFO

server:
  port: 3590
